version: '3.4'

volumes:
  data:

services:
  estetica.api:
    image: ${DOCKER_REGISTRY-}esteticaapi
    build:
      context: .
      dockerfile: src/Estetica.Api/Dockerfile
    environment:
      SERVIDOR : ${SERVIDOR}
      PORTA : ${PORTA}
      BANCO : ${BANCO}
      USUARIO : ${USUARIO}
      SENHA : ${SENHA}
      TIPOBANCO : ${TIPOBANCO}
    ports:
      - 5001:80
    expose:
      - 5001
    restart: on-failure