version: '3.4'

services:
  estetica.api:
    image: ${DOCKER_REGISTRY-}esteticaapi
    build:
      context: .
      dockerfile: src/Estetica.Api/Dockerfile
    environment:
      SERVIDOR: ${SERVIDOR}
      PORTA: ${PORTA}
      USUARIO: ${USUARIO}
      SENHA: ${SENHA}
      BANCO: ${BANCO}
    ports:
      - 5001:80
    expose:
      - 6000
    networks:
      rede_estetica:
        ipv4_address: 173.25.0.3
    restart: on-failure

networks:
  rede_estetica:
    name: rede_estetica
    driver: bridge
    ipam:
     config:
       - subnet: 173.25.0.0/16
         gateway: 173.25.0.1