version: '3.4'

services:
  vendafacil_ui:
    image: vendafacil_ui
    container_name: vendafacil_ui
    build:
      context: src/VendaFacil.UI
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    expose:
      - 4200
    restart: on-failure
    depends_on:
      - vendafacil.api
    networks:
      rede_vendafacil:
        ipv4_address: 173.25.0.4

  vendafacil.api:
    image: ${DOCKER_REGISTRY-}vendafacilapi
    container_name: vendafacil_api
    build:
      context: .
      dockerfile: src/VendaFacil.Api/Dockerfile
    environment:
      SERVIDOR: ${SERVIDOR}
      PORTA: ${PORTA}
      USUARIO: ${USUARIO}
      SENHA: ${SENHA}
      BANCO: ${BANCO}
    ports:
      - 6000:80
    expose:
      - 6000
    networks:
      rede_vendafacil:
        ipv4_address: 173.25.0.3
    restart: on-failure
    depends_on:
      - vendafacil_database
    
  vendafacil_database:
    image: postgres
    container_name: vendafacil_database
    environment:
      POSTGRES_USER: ${USUARIO}
      POSTGRES_PASSWORD: ${SENHA}
      PGDATA: /data/postgres
    ports:
      - "5402:5432"
    expose:
      - 5402
    networks:
      rede_vendafacil:
        ipv4_address: 173.25.0.2
    volumes:
       - /D/Databases/vendafacil_database/data:/var/lib/postgresql/data
    restart: on-failure

networks:
  rede_vendafacil:
    name: rede_vendafacil
    driver: bridge
    ipam:
     config:
       - subnet: 173.25.0.0/16
         gateway: 173.25.0.1