version: '3.4'

services:
  vendafacil_ui:
    image: vendafacil_ui
    container_name: vendafacil_ui
    build:
      context: src/VendaFacil.UI
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
    restart: on-failure
    depends_on:
      - vendafacil.api
    networks:
      rede_vendafacil:
        ipv4_address: 172.25.0.4

  vendafacil.api:
    image: ${DOCKER_REGISTRY-}vendafacilapi
    container_name: vendafacil_api
    build:
      context: .
      dockerfile: src/VendaFacil.Api/Dockerfile
    environment:
      SERVIDOR: "172.25.0.2"
      PORTA: "5401"
      USUARIO: "postgres"
      SENHA: "Postgres2019!"
      BANCO: "VendaFacilGestao"
    ports:
      - 3001:80
    networks:
      rede_vendafacil:
        ipv4_address: 172.25.0.3
    restart: on-failure
    depends_on:
      - vendafacil_database
    
  vendafacil_database:
    image: postgres
    container_name: vendafacil_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres2019!
      PGDATA: /data/postgres
    ports:
      - "5401:5432"
    expose:
      - 5401
    networks:
      rede_vendafacil:
        ipv4_address: 172.25.0.2
    volumes:
       - /D/Databases/vendafacil_database/data:/var/lib/postgresql/data
    restart: on-failure

networks:
  rede_vendafacil:
    name: rede_vendafacil
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1